#horror_books=["IT by Stephen King","The Haunting of Hill House by Shirley Jackson"]
#sci_fi_books=["The Martian by Andy Weir","The Time Machine by HG Wells"]
#romantic_books=["Pride and Prejudice by Jane Austen","The Song of Achilles by Madeline Miller"]
#comedy_books=["Catch-22 by Joseph Heller","The Hitchhiker's Guide to the Galaxy by Douglas Adams"]
#historical_books=["A Short History of Nearly Everything by Bill Bryson","Sapiens: A Brief History of Humankind by Yuval Noah Harari"]
#fantasy_books=["Harry Potter series by JK Rowling","The Lord of the Rings by J.R.R. Tolkien"]
#non_fiction_books=["Entangled Life: How Fungi Make Our Worlds, Change Our Minds & Shape Our Futures by Merlin Sheldrake","Braiding Sweetgrass: Indigenous Wisdom, Scientific Knowledge, and the Teachings of Plants by Robin Wall Kimmerer"]
#mystery_books=["The Girl with the Dragon Tattoo by Stieg Larsson","The Silent Patient by Alex Michaelides"]

#horror_movies=["The Shining by Stanley Kubrick","Get Out by Jordan Peele"]
#sci_fi_movies=["Interstellar by Christopher Nolan","TRON:Legacy by Joseph Kosinski"]
#romantic_movies=["Casablanca by Michael Curtiz","Pride and Prejudice by Joe Wright"]
#comedy_movies=["Groundhog Day by Harold Ramis","The Big Lebowski by Joel and Ethan Coen"]
#historical_movies=["Gladiator by Ridley Scott","Dunkirk by Christopher Nolan"]
#fantasy_movies=["Spirited Away by Hayao Miyazaki","Pan's Labyrinth by Guillermo del Toro"]
#non_fiction_movies=["Man on Wire by James Marsh","Free Solo by Jimmy Chin"]
#mystery_movies=["The Departed by Martin Scorsese","Inception by Christopher Nolan"]